#if !canImport(ObjectiveC)
import XCTest

extension JSONIntegerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONIntegerTests = [
        ("test_create_exclusiveMaximum", test_create_exclusiveMaximum),
        ("test_create_exclusiveMinimum", test_create_exclusiveMinimum),
        ("test_create_maximum", test_create_maximum),
        ("test_create_minimum", test_create_minimum),
        ("test_create_multipleOf", test_create_multipleOf),
        ("test_create_noValues", test_create_noValues),
    ]
}

extension JSONNumberTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONNumberTests = [
        ("test_create_exclusiveMaximum", test_create_exclusiveMaximum),
        ("test_create_exclusiveMinimum", test_create_exclusiveMinimum),
        ("test_create_maximum", test_create_maximum),
        ("test_create_minimum", test_create_minimum),
        ("test_create_multipleOf", test_create_multipleOf),
        ("test_create_noValues", test_create_noValues),
    ]
}

extension JSONObjectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONObjectTests = [
        ("test_decode_", test_decode_),
        ("test_decode_required", test_decode_required),
    ]
}

extension JSONSchemaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONSchemaTests = [
        ("testHasSchema", testHasSchema),
        ("testNoSchema", testNoSchema),
    ]
}

extension JSONStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONStringTests = [
        ("test_create_allValues", test_create_allValues),
        ("test_create_maximumLength", test_create_maximumLength),
        ("test_create_minimumLength", test_create_minimumLength),
        ("test_create_noValues", test_create_noValues),
        ("test_create_pattern", test_create_pattern),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONIntegerTests.__allTests__JSONIntegerTests),
        testCase(JSONNumberTests.__allTests__JSONNumberTests),
        testCase(JSONObjectTests.__allTests__JSONObjectTests),
        testCase(JSONSchemaTests.__allTests__JSONSchemaTests),
        testCase(JSONStringTests.__allTests__JSONStringTests),
    ]
}
#endif
