#if !canImport(ObjectiveC)
import XCTest

extension GeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeneratorTests = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GeneratorTests.__allTests__GeneratorTests),
    ]
}
#endif
